format_version: 10
pipelines:
  lightchaingocd:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a1f255f:
        git: https://github.com/stefanprisca/lightchain.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello World
                command: echo
                run_if: passed
