// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lightpeer.proto

package lightpeer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lightblock_BlockType int32

const (
	Lightblock_NETWORK Lightblock_BlockType = 0
	Lightblock_CLIENT  Lightblock_BlockType = 1
)

var Lightblock_BlockType_name = map[int32]string{
	0: "NETWORK",
	1: "CLIENT",
}

var Lightblock_BlockType_value = map[string]int32{
	"NETWORK": 0,
	"CLIENT":  1,
}

func (x Lightblock_BlockType) String() string {
	return proto.EnumName(Lightblock_BlockType_name, int32(x))
}

func (Lightblock_BlockType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{0, 0}
}

type Lightblock struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Payload              []byte               `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	PrevID               string               `protobuf:"bytes,3,opt,name=PrevID,proto3" json:"PrevID,omitempty"`
	Type                 Lightblock_BlockType `protobuf:"varint,9,opt,name=Type,proto3,enum=Lightblock_BlockType" json:"Type,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,10,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Lightblock) Reset()         { *m = Lightblock{} }
func (m *Lightblock) String() string { return proto.CompactTextString(m) }
func (*Lightblock) ProtoMessage()    {}
func (*Lightblock) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{0}
}

func (m *Lightblock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lightblock.Unmarshal(m, b)
}
func (m *Lightblock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lightblock.Marshal(b, m, deterministic)
}
func (m *Lightblock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lightblock.Merge(m, src)
}
func (m *Lightblock) XXX_Size() int {
	return xxx_messageInfo_Lightblock.Size(m)
}
func (m *Lightblock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lightblock.DiscardUnknown(m)
}

var xxx_messageInfo_Lightblock proto.InternalMessageInfo

func (m *Lightblock) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Lightblock) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Lightblock) GetPrevID() string {
	if m != nil {
		return m.PrevID
	}
	return ""
}

func (m *Lightblock) GetType() Lightblock_BlockType {
	if m != nil {
		return m.Type
	}
	return Lightblock_NETWORK
}

func (m *Lightblock) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type JoinRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{1}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type JoinResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{2}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ConnectRequest struct {
	Peer                 *PeerInfo `protobuf:"bytes,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{3}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetPeer() *PeerInfo {
	if m != nil {
		return m.Peer
	}
	return nil
}

type PeerInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{4}
}

func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PeerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PersistRequest struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersistRequest) Reset()         { *m = PersistRequest{} }
func (m *PersistRequest) String() string { return proto.CompactTextString(m) }
func (*PersistRequest) ProtoMessage()    {}
func (*PersistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{5}
}

func (m *PersistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistRequest.Unmarshal(m, b)
}
func (m *PersistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistRequest.Marshal(b, m, deterministic)
}
func (m *PersistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistRequest.Merge(m, src)
}
func (m *PersistRequest) XXX_Size() int {
	return xxx_messageInfo_PersistRequest.Size(m)
}
func (m *PersistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PersistRequest proto.InternalMessageInfo

func (m *PersistRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PersistResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersistResponse) Reset()         { *m = PersistResponse{} }
func (m *PersistResponse) String() string { return proto.CompactTextString(m) }
func (*PersistResponse) ProtoMessage()    {}
func (*PersistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{6}
}

func (m *PersistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistResponse.Unmarshal(m, b)
}
func (m *PersistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistResponse.Marshal(b, m, deterministic)
}
func (m *PersistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistResponse.Merge(m, src)
}
func (m *PersistResponse) XXX_Size() int {
	return xxx_messageInfo_PersistResponse.Size(m)
}
func (m *PersistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PersistResponse proto.InternalMessageInfo

func (m *PersistResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type EmptyQueryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyQueryRequest) Reset()         { *m = EmptyQueryRequest{} }
func (m *EmptyQueryRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyQueryRequest) ProtoMessage()    {}
func (*EmptyQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{7}
}

func (m *EmptyQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyQueryRequest.Unmarshal(m, b)
}
func (m *EmptyQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyQueryRequest.Marshal(b, m, deterministic)
}
func (m *EmptyQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyQueryRequest.Merge(m, src)
}
func (m *EmptyQueryRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyQueryRequest.Size(m)
}
func (m *EmptyQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyQueryRequest proto.InternalMessageInfo

type QueryResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{8}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type NewBlockRequest struct {
	Contents             string   `protobuf:"bytes,1,opt,name=Contents,proto3" json:"Contents,omitempty"`
	UID                  string   `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlockRequest) Reset()         { *m = NewBlockRequest{} }
func (m *NewBlockRequest) String() string { return proto.CompactTextString(m) }
func (*NewBlockRequest) ProtoMessage()    {}
func (*NewBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{9}
}

func (m *NewBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockRequest.Unmarshal(m, b)
}
func (m *NewBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockRequest.Marshal(b, m, deterministic)
}
func (m *NewBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockRequest.Merge(m, src)
}
func (m *NewBlockRequest) XXX_Size() int {
	return xxx_messageInfo_NewBlockRequest.Size(m)
}
func (m *NewBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockRequest proto.InternalMessageInfo

func (m *NewBlockRequest) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *NewBlockRequest) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type NewBlockResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlockResponse) Reset()         { *m = NewBlockResponse{} }
func (m *NewBlockResponse) String() string { return proto.CompactTextString(m) }
func (*NewBlockResponse) ProtoMessage()    {}
func (*NewBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcee3e88f49c2881, []int{10}
}

func (m *NewBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockResponse.Unmarshal(m, b)
}
func (m *NewBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockResponse.Marshal(b, m, deterministic)
}
func (m *NewBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockResponse.Merge(m, src)
}
func (m *NewBlockResponse) XXX_Size() int {
	return xxx_messageInfo_NewBlockResponse.Size(m)
}
func (m *NewBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockResponse proto.InternalMessageInfo

func (m *NewBlockResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterEnum("Lightblock_BlockType", Lightblock_BlockType_name, Lightblock_BlockType_value)
	proto.RegisterType((*Lightblock)(nil), "Lightblock")
	proto.RegisterType((*JoinRequest)(nil), "JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "JoinResponse")
	proto.RegisterType((*ConnectRequest)(nil), "ConnectRequest")
	proto.RegisterType((*PeerInfo)(nil), "PeerInfo")
	proto.RegisterType((*PersistRequest)(nil), "PersistRequest")
	proto.RegisterType((*PersistResponse)(nil), "PersistResponse")
	proto.RegisterType((*EmptyQueryRequest)(nil), "EmptyQueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
	proto.RegisterType((*NewBlockRequest)(nil), "NewBlockRequest")
	proto.RegisterType((*NewBlockResponse)(nil), "NewBlockResponse")
}

func init() {
	proto.RegisterFile("lightpeer.proto", fileDescriptor_fcee3e88f49c2881)
}

var fileDescriptor_fcee3e88f49c2881 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x8f, 0x93, 0x40,
	0x14, 0x2d, 0xdd, 0xda, 0x5d, 0x2e, 0x2d, 0x65, 0xc7, 0x68, 0x1a, 0x12, 0xa3, 0x99, 0x18, 0x75,
	0x8d, 0x0e, 0x06, 0x1f, 0xf4, 0xc5, 0x18, 0x77, 0xed, 0x43, 0xb5, 0xc1, 0x4a, 0xba, 0x31, 0xf1,
	0xc5, 0xd0, 0x65, 0x5a, 0xc9, 0x52, 0x06, 0x61, 0x70, 0xc3, 0x2f, 0xf0, 0x5f, 0xfa, 0x5b, 0x1c,
	0x06, 0x86, 0x6d, 0x6b, 0x36, 0xfb, 0x42, 0xee, 0xb9, 0x9c, 0xb9, 0x1f, 0xe7, 0xcc, 0xc0, 0x28,
	0x8e, 0xd6, 0x3f, 0x79, 0x4a, 0x69, 0x46, 0xd2, 0x8c, 0x71, 0x66, 0x3f, 0x5c, 0x33, 0xb6, 0x8e,
	0xa9, 0x23, 0xd1, 0xb2, 0x58, 0x39, 0x3c, 0xda, 0xd0, 0x9c, 0x07, 0x9b, 0xb4, 0x26, 0xe0, 0xbf,
	0x1a, 0xc0, 0xac, 0x3a, 0xb4, 0x8c, 0xd9, 0xc5, 0x25, 0x32, 0xa1, 0x3b, 0xfd, 0x38, 0xd6, 0x1e,
	0x69, 0xcf, 0x74, 0x5f, 0x44, 0x68, 0x0c, 0x87, 0xf3, 0xa0, 0x8c, 0x59, 0x10, 0x8e, 0xbb, 0x22,
	0x39, 0xf0, 0x15, 0x44, 0xf7, 0xa1, 0x3f, 0xcf, 0xe8, 0x6f, 0xc1, 0x3e, 0x90, 0xec, 0x06, 0xa1,
	0x13, 0xe8, 0x2d, 0xca, 0x94, 0x8e, 0x75, 0x91, 0x35, 0xdd, 0x7b, 0xe4, 0xba, 0x38, 0x39, 0xad,
	0xbe, 0xd5, 0x4f, 0x5f, 0x52, 0xd0, 0x3b, 0x18, 0xc4, 0x41, 0xce, 0x7f, 0x14, 0x69, 0x18, 0x70,
	0x1a, 0x8e, 0x41, 0x1c, 0x31, 0x5c, 0x9b, 0xd4, 0x33, 0x13, 0x35, 0x33, 0x59, 0xa8, 0x99, 0x7d,
	0xa3, 0xe2, 0x9f, 0xd7, 0x74, 0xfc, 0x18, 0xf4, 0xb6, 0x22, 0x32, 0xe0, 0xd0, 0x9b, 0x2c, 0xbe,
	0x7d, 0xf1, 0x3f, 0x5b, 0x1d, 0x04, 0xd0, 0x3f, 0x9b, 0x4d, 0x27, 0xde, 0xc2, 0xd2, 0xf0, 0x53,
	0x30, 0x3e, 0xb1, 0x28, 0xf1, 0xe9, 0xaf, 0x42, 0x14, 0xa9, 0x16, 0xfa, 0x10, 0x86, 0x19, 0xcd,
	0xf3, 0x66, 0x4b, 0x05, 0xf1, 0x13, 0x18, 0xd4, 0xc4, 0x3c, 0x65, 0x49, 0x4e, 0xab, 0x05, 0x45,
	0x5c, 0xc4, 0xbc, 0x21, 0x36, 0x08, 0x3b, 0x60, 0x9e, 0xb1, 0x24, 0xa1, 0x17, 0x5c, 0xd5, 0x7c,
	0x00, 0xbd, 0xb9, 0x90, 0x5c, 0xf2, 0x0c, 0x57, 0x27, 0x15, 0x98, 0x26, 0x2b, 0xe6, 0xcb, 0x34,
	0x7e, 0x0b, 0x47, 0x2a, 0x73, 0x73, 0x7b, 0x84, 0xa0, 0xe7, 0x05, 0x1b, 0x2a, 0x65, 0xd6, 0x7d,
	0x19, 0xe3, 0xe7, 0x60, 0xce, 0x69, 0x96, 0x47, 0x39, 0xdf, 0x1a, 0x5f, 0xf9, 0xa1, 0xed, 0xf8,
	0x81, 0x5f, 0xc2, 0xa8, 0xe5, 0x36, 0x1b, 0xd8, 0x70, 0xa4, 0xe2, 0xa6, 0x5b, 0x8b, 0xf1, 0x5d,
	0x38, 0x9e, 0x6c, 0x52, 0x5e, 0x7e, 0x2d, 0x68, 0x56, 0x36, 0xd5, 0xf1, 0x09, 0x0c, 0x1b, 0xdc,
	0x54, 0xb8, 0xb9, 0xdd, 0x7b, 0x18, 0x79, 0xf4, 0x4a, 0xea, 0xaf, 0x66, 0x13, 0xed, 0x84, 0x30,
	0x9c, 0x26, 0x5c, 0x2d, 0xd7, 0x62, 0x64, 0xc1, 0xc1, 0xb9, 0xb8, 0x2a, 0xf5, 0x72, 0x55, 0x88,
	0x09, 0x58, 0xd7, 0x05, 0x6e, 0x1f, 0xd8, 0xfd, 0xd3, 0x05, 0x7d, 0xa6, 0x6e, 0x37, 0x7a, 0x51,
	0xbb, 0xea, 0x51, 0x7e, 0xc5, 0xb2, 0x4b, 0x34, 0x20, 0x5b, 0x1e, 0xdb, 0x43, 0xb2, 0x6d, 0x24,
	0xee, 0x20, 0xb7, 0xb5, 0x4c, 0xb4, 0xac, 0xbc, 0x40, 0x23, 0xb2, 0xeb, 0xa1, 0x6d, 0x6c, 0x5d,
	0x54, 0xdc, 0x79, 0xa5, 0x21, 0x22, 0x56, 0xaf, 0xf5, 0x14, 0xe4, 0x5d, 0x17, 0x6c, 0x8b, 0xec,
	0x49, 0x2d, 0x7a, 0x38, 0x70, 0x47, 0x6a, 0x87, 0x10, 0xf9, 0x4f, 0x58, 0xdb, 0x24, 0x3b, 0xba,
	0xca, 0x06, 0x6f, 0xc0, 0xf4, 0x18, 0x8f, 0x56, 0xa5, 0x92, 0x01, 0x59, 0x64, 0x4f, 0x52, 0xfb,
	0x98, 0xec, 0x6b, 0x84, 0x3b, 0xa7, 0xa3, 0xef, 0xc3, 0x20, 0x8d, 0x9c, 0xf6, 0xa9, 0x2f, 0xfb,
	0xf2, 0xa5, 0xbc, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x14, 0xc9, 0x76, 0xfe, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LightpeerClient is the client API for Lightpeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LightpeerClient interface {
	JoinNetwork(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	ConnectNewPeer(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (Lightpeer_ConnectNewPeerClient, error)
	Persist(ctx context.Context, in *PersistRequest, opts ...grpc.CallOption) (*PersistResponse, error)
	Query(ctx context.Context, in *EmptyQueryRequest, opts ...grpc.CallOption) (Lightpeer_QueryClient, error)
	NotifyNewBlock(ctx context.Context, in *NewBlockRequest, opts ...grpc.CallOption) (*NewBlockResponse, error)
}

type lightpeerClient struct {
	cc grpc.ClientConnInterface
}

func NewLightpeerClient(cc grpc.ClientConnInterface) LightpeerClient {
	return &lightpeerClient{cc}
}

func (c *lightpeerClient) JoinNetwork(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/Lightpeer/JoinNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightpeerClient) ConnectNewPeer(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (Lightpeer_ConnectNewPeerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lightpeer_serviceDesc.Streams[0], "/Lightpeer/ConnectNewPeer", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightpeerConnectNewPeerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lightpeer_ConnectNewPeerClient interface {
	Recv() (*Lightblock, error)
	grpc.ClientStream
}

type lightpeerConnectNewPeerClient struct {
	grpc.ClientStream
}

func (x *lightpeerConnectNewPeerClient) Recv() (*Lightblock, error) {
	m := new(Lightblock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightpeerClient) Persist(ctx context.Context, in *PersistRequest, opts ...grpc.CallOption) (*PersistResponse, error) {
	out := new(PersistResponse)
	err := c.cc.Invoke(ctx, "/Lightpeer/Persist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightpeerClient) Query(ctx context.Context, in *EmptyQueryRequest, opts ...grpc.CallOption) (Lightpeer_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lightpeer_serviceDesc.Streams[1], "/Lightpeer/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightpeerQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lightpeer_QueryClient interface {
	Recv() (*QueryResponse, error)
	grpc.ClientStream
}

type lightpeerQueryClient struct {
	grpc.ClientStream
}

func (x *lightpeerQueryClient) Recv() (*QueryResponse, error) {
	m := new(QueryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightpeerClient) NotifyNewBlock(ctx context.Context, in *NewBlockRequest, opts ...grpc.CallOption) (*NewBlockResponse, error) {
	out := new(NewBlockResponse)
	err := c.cc.Invoke(ctx, "/Lightpeer/NotifyNewBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightpeerServer is the server API for Lightpeer service.
type LightpeerServer interface {
	JoinNetwork(context.Context, *JoinRequest) (*JoinResponse, error)
	ConnectNewPeer(*ConnectRequest, Lightpeer_ConnectNewPeerServer) error
	Persist(context.Context, *PersistRequest) (*PersistResponse, error)
	Query(*EmptyQueryRequest, Lightpeer_QueryServer) error
	NotifyNewBlock(context.Context, *NewBlockRequest) (*NewBlockResponse, error)
}

// UnimplementedLightpeerServer can be embedded to have forward compatible implementations.
type UnimplementedLightpeerServer struct {
}

func (*UnimplementedLightpeerServer) JoinNetwork(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinNetwork not implemented")
}
func (*UnimplementedLightpeerServer) ConnectNewPeer(req *ConnectRequest, srv Lightpeer_ConnectNewPeerServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectNewPeer not implemented")
}
func (*UnimplementedLightpeerServer) Persist(ctx context.Context, req *PersistRequest) (*PersistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Persist not implemented")
}
func (*UnimplementedLightpeerServer) Query(req *EmptyQueryRequest, srv Lightpeer_QueryServer) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedLightpeerServer) NotifyNewBlock(ctx context.Context, req *NewBlockRequest) (*NewBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyNewBlock not implemented")
}

func RegisterLightpeerServer(s *grpc.Server, srv LightpeerServer) {
	s.RegisterService(&_Lightpeer_serviceDesc, srv)
}

func _Lightpeer_JoinNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightpeerServer).JoinNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightpeer/JoinNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightpeerServer).JoinNetwork(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightpeer_ConnectNewPeer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightpeerServer).ConnectNewPeer(m, &lightpeerConnectNewPeerServer{stream})
}

type Lightpeer_ConnectNewPeerServer interface {
	Send(*Lightblock) error
	grpc.ServerStream
}

type lightpeerConnectNewPeerServer struct {
	grpc.ServerStream
}

func (x *lightpeerConnectNewPeerServer) Send(m *Lightblock) error {
	return x.ServerStream.SendMsg(m)
}

func _Lightpeer_Persist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightpeerServer).Persist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightpeer/Persist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightpeerServer).Persist(ctx, req.(*PersistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightpeer_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightpeerServer).Query(m, &lightpeerQueryServer{stream})
}

type Lightpeer_QueryServer interface {
	Send(*QueryResponse) error
	grpc.ServerStream
}

type lightpeerQueryServer struct {
	grpc.ServerStream
}

func (x *lightpeerQueryServer) Send(m *QueryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Lightpeer_NotifyNewBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightpeerServer).NotifyNewBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightpeer/NotifyNewBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightpeerServer).NotifyNewBlock(ctx, req.(*NewBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lightpeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Lightpeer",
	HandlerType: (*LightpeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinNetwork",
			Handler:    _Lightpeer_JoinNetwork_Handler,
		},
		{
			MethodName: "Persist",
			Handler:    _Lightpeer_Persist_Handler,
		},
		{
			MethodName: "NotifyNewBlock",
			Handler:    _Lightpeer_NotifyNewBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectNewPeer",
			Handler:       _Lightpeer_ConnectNewPeer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Query",
			Handler:       _Lightpeer_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lightpeer.proto",
}
